### ISSUE TITLE
004005000-app.ja.md の説明文の修正依頼

### ISSUE THREAD

**Issue by cats-servant** [RepsonaHQ/repsona-content-help#4]
> 移動先でも Repsona モバイルアプリで最新の状態を確認できます。モバイルアプリをダウンロードして**タスクのとコミュニケーション**を持ち歩きましょう。

下記のような意味でしょうか？
1. タスクとコミュニケーション
2. タスクとメンバーとのコミュニケーション手段

**Comment by GussieTech** [comment]
@cats-servant ご指摘ありがとうございます、何を書きたかったのだろう😂

> タスクとメンバーとのコミュニケーション手段

こちらに修正いたします
